# Generated by Django 3.1.4 on 2020-12-14 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20201214_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('form', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_time', models.DateTimeField(default=datetime.datetime(2020, 12, 14, 17, 20, 40, 937357))),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.candidat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election.profile')),
            ],
        ),
    ]
