# Generated by Django 3.1.4 on 2020-12-14 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_candidat_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 17, 22, 19, 864504, tzinfo=utc)),
        ),
    ]
