# Generated by Django 3.1.4 on 2020-12-20 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20201214_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 8, 47, 0, 776476, tzinfo=utc)),
        ),
    ]
